# Generated by Django 5.1.5 on 2025-01-27 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='igl.navmenu'),
        ),
        migrations.AlterField(
            model_name='navmenu',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
