# Generated by Django 5.1.5 on 2025-01-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0002_navmenu_parent_alter_navmenu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('button_text', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='cover_section_images/')),
            ],
        ),
    ]
