# Generated by Django 5.1.5 on 2025-01-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0004_contactbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_ShedulSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Call or visit us at one of our different locations.', max_length=255)),
                ('description', models.TextField(default='Amet minim mollit non deserunt ullamco est aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit amet minim mollit on.')),
                ('button_text', models.CharField(default='Schedule a call', max_length=100)),
                ('button_url', models.URLField(blank=True, default='#', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_LocationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('map_url', models.URLField(blank=True, default='#', null=True)),
                ('image', models.ImageField(upload_to='locations/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='igl.contact_shedulsection')),
            ],
        ),
    ]
