# Generated by Django 5.1.5 on 2025-01-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0005_contact_shedulsection_contact_locationsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='City name.', max_length=100)),
                ('address', models.TextField(help_text='Full address of the location.', max_length=255)),
                ('map_embed_code', models.TextField(blank=True, help_text='Google Maps iframe embed code for the location. Paste the iframe code from Google Maps.', null=True)),
                ('phone_number', models.CharField(help_text='Phone number for the location.', max_length=20)),
                ('image', models.ImageField(help_text='Image or background for the location.', upload_to='locations/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading text for the contact section.', max_length=255)),
                ('description', models.TextField(help_text='Short description or introduction.', max_length=255)),
                ('button_text', models.CharField(help_text='Text for the call-to-action button.', max_length=100)),
                ('button_link', models.URLField(blank=True, help_text='URL the button redirects to.', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_LocationSection',
        ),
        migrations.DeleteModel(
            name='Contact_ShedulSection',
        ),
    ]
