# Generated by Django 5.1.5 on 2025-01-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0008_contact_fromdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
