# Generated by Django 5.1.5 on 2025-01-29 11:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0013_jobposting_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='full_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='short_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
