# Generated by Django 5.1.5 on 2025-01-30 04:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0014_alter_jobposting_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary',
            field=models.CharField(help_text='Specify salary range (e.g., 30,000 - 50,000 BDT)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='full_description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
