# Generated by Django 5.1.5 on 2025-01-30 04:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0015_jobposting_salary_alter_jobposting_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='full_description',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
