# Generated by Django 5.1.5 on 2025-01-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0016_alter_jobposting_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(default='dhaka', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
