# Generated by Django 5.1.5 on 2025-01-30 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0018_album_remove_gallery_title_gallery_album'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Gallery_Album',
        ),
        migrations.CreateModel(
            name='Gallery_AlbumDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='igl.gallery_album')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
