# Generated by Django 5.1.5 on 2025-01-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0019_rename_album_gallery_album_gallery_albumdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='business_strength/')),
                ('icon', models.ImageField(upload_to='business_strength/icons/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
