# Generated by Django 5.1.5 on 2025-01-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0020_businessstrength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstrength',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
