# Generated by Django 5.1.5 on 2025-02-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0021_alter_businessstrength_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Chairman', 'Chairman'), ('MD', 'Managing Director')], default='Chairman', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
