# Generated by Django 5.1.5 on 2025-02-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0023_remove_bod_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bod',
            name='role',
            field=models.CharField(default='Chairman', max_length=100),
        ),
    ]
