# Generated by Django 5.1.5 on 2025-02-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0024_alter_bod_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoverSection',
            new_name='HomeBanner',
        ),
    ]
