# Generated by Django 5.1.5 on 2025-02-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0025_rename_coversection_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('background_image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
