# Generated by Django 5.1.5 on 2025-02-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0028_bussinessbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog', max_length=255)),
                ('background_image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
