# Generated by Django 5.1.5 on 2025-02-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0032_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/industry_icons/'),
        ),
    ]
