# Generated by Django 5.1.5 on 2025-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0033_alter_industry_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonToChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('🎯', 'Target (🎯)'), ('✉️', 'Envelope (✉️)'), ('🚀', 'Rocket (🚀)'), ('💡', 'Lightbulb (💡)'), ('📈', 'Chart Growth (📈)'), ('⚙️', 'Gear (⚙️)'), ('🔗', 'Link (🔗)'), ('🎨', 'Palette (🎨)'), ('🔍', 'Magnifying Glass (🔍)'), ('🛡️', 'Shield (🛡️)'), ('🏆', 'Trophy (🏆)'), ('🤝', 'Handshake (🤝)'), ('💎', 'Diamond (💎)'), ('📌', 'Push Pin (📌)'), ('🔬', 'Microscope (🔬)')], default='🎯', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the order of display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
