# Generated by Django 5.1.5 on 2025-02-03 09:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0036_homeintro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeintro',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
