# Generated by Django 5.1.5 on 2025-02-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0037_alter_homeintro_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Large main image (800x600)', upload_to='career_images/')),
                ('group_image', models.ImageField(help_text='Group image (400x300)', upload_to='career_images/')),
                ('activity_image1', models.ImageField(help_text='First activity image (300x200)', upload_to='career_images/')),
                ('activity_image2', models.ImageField(help_text='Second activity image (300x200)', upload_to='career_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career Page Images',
                'verbose_name_plural': 'Career Page Images',
            },
        ),
    ]
