# Generated by Django 5.1.5 on 2025-02-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0039_homebannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Enter the YouTube or Vimeo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
