# Generated by Django 5.1.5 on 2025-02-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0040_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='location',
        ),
    ]
