# Generated by Django 5.1.5 on 2025-02-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0041_remove_jobposting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong')], default='dhaka', max_length=100),
        ),
    ]
