# Generated by Django 5.1.5 on 2025-02-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0042_jobposting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='department',
            field=models.CharField(default='IT', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('SEO', 'SEO'), ('SOFTWARE', 'Software'), ('TELESALES', 'Telesales'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts')], default='IT', max_length=50),
        ),
    ]
