# Generated by Django 5.1.5 on 2025-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0043_jobapplication_department_jobapplication_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_fromdata',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact_fromdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact_fromdata',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact_fromdata',
            name='message',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
