# Generated by Django 5.1.5 on 2025-02-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0044_contact_fromdata_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FELNA_TECH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='felna_tech/')),
            ],
        ),
        migrations.CreateModel(
            name='IGL_HOST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='igl_host/')),
            ],
        ),
        migrations.CreateModel(
            name='IGL_WEB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='igl_web/')),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT_VISA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='student_visa/')),
            ],
        ),
    ]
