# Generated by Django 4.2.18 on 2025-02-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0046_alter_felna_tech_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientReview',
        ),
    ]
