# Generated by Django 5.1.5 on 2025-02-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0046_alter_felna_tech_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeintro',
            name='image2',
        ),
    ]
