# Generated by Django 5.1.5 on 2025-02-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0047_remove_homeintro_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(default='No Image Uploaded', upload_to='about_section/'),
        ),
    ]
