# Generated by Django 4.2.18 on 2025-02-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0047_delete_clientreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogBanner',
        ),
    ]
