# Generated by Django 4.2.18 on 2025-02-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0048_delete_blog_delete_blogbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeintro',
            name='image2',
        ),
    ]
