# Generated by Django 4.2.18 on 2025-02-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0049_remove_homeintro_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(default='No Image Uploaded', null=True, upload_to='about_section/'),
        ),
    ]
