# Generated by Django 5.1.5 on 2025-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0049_bod_pdf_bod_portfolio_link_alter_bod_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bod',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
