# Generated by Django 4.2.18 on 2025-02-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0050_remove_aboutsection_title_aboutsection_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessStrength',
        ),
    ]
