# Generated by Django 4.2.18 on 2025-02-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0051_delete_businessstrength'),
    ]

    operations = [
        migrations.AddField(
            model_name='bod',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bod_pdfs/'),
        ),
        migrations.AddField(
            model_name='bod',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bod',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bod',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bod',
            name='image',
            field=models.ImageField(upload_to='bod_images/'),
        ),
        migrations.AlterField(
            model_name='bod',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bod',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
