# Generated by Django 5.1.5 on 2025-02-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0051_remove_bod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bod',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
