# Generated by Django 4.2.18 on 2025-02-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0052_bod_pdf_bod_portfolio_link_bod_slug_alter_bod_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pdf',
            field=models.FileField(blank=True, default='Not Uploaded', null=True, upload_to='bod_pdfs/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='portfolio_link',
            field=models.URLField(blank=True, default='Not Uploaded', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
