# Generated by Django 5.1.5 on 2025-02-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0052_bod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pdf',
            field=models.FileField(blank=True, default='Not Uploaded', null=True, upload_to='bod_pdfs/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='portfolio_link',
            field=models.URLField(blank=True, default='Not Uploaded', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
