# Generated by Django 4.2.18 on 2025-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0053_staff_bio_staff_pdf_staff_portfolio_link_staff_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeamBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Team', max_length=255)),
                ('background_image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
