# Generated by Django 4.2.18 on 2025-02-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0054_ourteambanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_album',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
