# Generated by Django 4.2.18 on 2025-02-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0055_gallery_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='Male', max_length=10),
        ),
    ]
