# Generated by Django 5.1.5 on 2025-02-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0056_alter_jobapplication_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SisterConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='business_strength/')),
                ('icon', models.ImageField(upload_to='business_strength/icons/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
