# Generated by Django 5.1.5 on 2025-02-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0057_sisterconcern'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisterconcern',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
