# Generated by Django 5.1.5 on 2025-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0058_sisterconcern_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeServe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='weserve_icons/')),
            ],
        ),
    ]
