# Generated by Django 5.1.5 on 2025-03-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0060_remove_contact_schedule_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_location',
            name='TNT_number',
            field=models.CharField(blank=True, help_text='TNT number for the location.', max_length=20, null=True),
        ),
    ]
