# Generated by Django 5.1.5 on 2025-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0061_contact_location_tnt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
