# Generated by Django 5.1.5 on 2025-04-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0062_jobapplication_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
