# Generated by Django 5.1.5 on 2025-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igl', '0063_jobposting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('SEO', 'SEO'), ('SOFTWARE', 'Software'), ('TELESALES', 'Telesales'), ('HR', 'HR'), ('ACCOUNTS', 'Accounts'), ('CORPORATE SALES', 'Corporate Sales')], default='IT', max_length=50),
        ),
    ]
